# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-04 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20180604_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(choices=[('FF', 'Fast food'), ('SF', 'Slow food')], max_length=120),
        ),
    ]
