# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-14 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import restaurant.validators


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20180605_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[restaurant.validators.validate_category]),
        ),
    ]
